### ISSUE TITLE
我是个swoole新手，docker pull之后如何运行？谢谢

### ISSUE THREAD

**Issue by scfobao** [keaixiaou/zhttp#2]
如题

**Comment by keaixiaou** [comment]
https://docs.docker.com/get-started/

**Comment by scfobao** [comment]
###Dockerfile。如下
FROM keaixiaou/zhttp:1.0
WORKDIR /app
ADD . /app
RUN composer install
 
CMD ["php", "webroot/main.php","start"]
EXPOSE 80

**Comment by scfobao** [comment]
但有个问题。
docker run -p 4000:80 swoole_aoduo。
跑起来，得到个这样的结果
Service startting success!
http://localhost:4000/test/1.无法访问。这是怎么回事

**Comment by keaixiaou** [comment]
这个可以谷歌一下
